######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : checkpoint-wf, Index = 0, Count = null
# SUBMIT FILE NAME : create_dir_checkpoint-wf_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a97a7982-524d-4d25-9ed0-1d39e1379b59 PEGASUS_WF_LABEL=checkpoint-wf PEGASUS_DAG_JOB_ID=create_dir_checkpoint-wf_0_local PEGASUS_SITE=local PEGASUS_BIN_DIR=/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::dirmanager -N null -i - -R local  -L checkpoint-wf -T 2020-07-20T17:38:31+00:00 pegasus-transfer "
error = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0001//00/00/create_dir_checkpoint-wf_0_local.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-local.sh
input = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0001//00/00/create_dir_checkpoint-wf_0_local.in
log = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0001/checkpoint-wf-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0001//00/00/create_dir_checkpoint-wf_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a97a7982-524d-4d25-9ed0-1d39e1379b59"
+pegasus_wf_uuid = "a97a7982-524d-4d25-9ed0-1d39e1379b59"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "checkpoint-wf-0"
+pegasus_wf_time = "20200720T173832+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_checkpoint-wf_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
