######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : harry-potter-text-analysis, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_1_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=c6f62849-2dcd-4eeb-8247-61a14413db71 PEGASUS_WF_LABEL=harry-potter-text-analysis PEGASUS_DAG_JOB_ID=register_local_1_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L harry-potter-text-analysis -T 2020-08-10T21:03:03+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005/pegasus.5753679767146223155.properties -v --meta /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005/00/00/sort_ID0000002.meta --insert /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005/00/00/register_local_1_0.in"
error = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005//00/00/register_local_1_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005/harry-potter-text-analysis-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0005//00/00/register_local_1_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "c6f62849-2dcd-4eeb-8247-61a14413db71"
+pegasus_wf_uuid = "c6f62849-2dcd-4eeb-8247-61a14413db71"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "harry-potter-text-analysis-0"
+pegasus_wf_time = "20200810T210304+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_1_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
