######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Increment, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=88190c7e-43b1-4eae-85c7-b98e80fe8737 PEGASUS_WF_LABEL=Increment PEGASUS_DAG_JOB_ID=register_local_0_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L Increment -T 2020-07-12T06:02:13+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001/pegasus.3602717352314270392.properties -v --meta /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001/00/00/increment_py_ID0000001.meta --insert /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001/00/00/register_local_0_0.in"
error = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001//00/00/register_local_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001/Increment-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0001//00/00/register_local_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "88190c7e-43b1-4eae-85c7-b98e80fe8737"
+pegasus_wf_uuid = "88190c7e-43b1-4eae-85c7-b98e80fe8737"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Increment-0"
+pegasus_wf_time = "20200712T060213+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_0_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
