######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : checkpoint-wf, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=b16a86b6-71f2-48e6-8306-18e7cb47f190 PEGASUS_WF_LABEL=checkpoint-wf PEGASUS_DAG_JOB_ID=register_local_0_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L checkpoint-wf -T 2020-07-20T17:11:16+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001/pegasus.7516635538059009488.properties -v --meta /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001/00/00/checkpoint_program_py_ID0000001.meta --insert /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001/00/00/register_local_0_0.in"
error = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001//00/00/register_local_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001/checkpoint-wf-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0001//00/00/register_local_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "b16a86b6-71f2-48e6-8306-18e7cb47f190"
+pegasus_wf_uuid = "b16a86b6-71f2-48e6-8306-18e7cb47f190"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "checkpoint-wf-0"
+pegasus_wf_time = "20200720T171117+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_0_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
