pegasus: '5.0'
name: hello-world
jobs:
- type: job
  name: echo
  id: ID0000001
  stdout: out.txt
  arguments: []
  uses:
  - {lfn: f.a, type: input}
  - {lfn: out.txt, type: output, stageOut: true, registerReplica: true}
jobDependencies: []
