######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Cats_and_Dogs, Index = 0, Count = null
# SUBMIT FILE NAME : Augmentation_py_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=95280ca4-598e-4f2a-a511-7f344f4a0521 PEGASUS_WF_LABEL=Cats_and_Dogs PEGASUS_DAG_JOB_ID=Augmentation_py_ID0000002 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/Augmentation_py_ID0000002.err
executable = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/Augmentation_py_ID0000002.sh
initialdir = /home/scitech/shared-data/CatsAndDogs/wf-scratch/LOCAL/scitech/pegasus/Cats_and_Dogs/run0001
log = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/Cats_and_Dogs-0.log
notification = NEVER
output = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/Augmentation_py_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = labels.txt,resized_images.txt,Augmentation_py,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/stage_in_remote_local_1_0.meta,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/preprocess1_py_ID0000001.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = aug_labels.txt,augmentation.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "95280ca4-598e-4f2a-a511-7f344f4a0521"
+pegasus_wf_uuid = "95280ca4-598e-4f2a-a511-7f344f4a0521"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Cats_and_Dogs-0"
+pegasus_wf_time = "20200729T160640+0000"
+pegasus_wf_xformation = "Augmentation.py"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "Augmentation_py_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
