######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Cats_and_Dogs, Index = 0, Count = null
# SUBMIT FILE NAME : create_dir_Cats_and_Dogs_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=b6e91872-355a-408f-81c2-05325befbeac PEGASUS_WF_LABEL=Cats_and_Dogs PEGASUS_DAG_JOB_ID=create_dir_Cats_and_Dogs_0_local PEGASUS_SITE=local"
arguments = " -n pegasus::dirmanager -N null -i - -R local  -L Cats_and_Dogs -T 2020-08-07T18:41:39+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-transfer "
error = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/create_dir_Cats_and_Dogs_0_local.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
input = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/create_dir_Cats_and_Dogs_0_local.in
log = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/Cats_and_Dogs-0.log
notification = NEVER
output = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/create_dir_Cats_and_Dogs_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "b6e91872-355a-408f-81c2-05325befbeac"
+pegasus_wf_uuid = "b6e91872-355a-408f-81c2-05325befbeac"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Cats_and_Dogs-0"
+pegasus_wf_time = "20200807T184139+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_Cats_and_Dogs_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
