######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Cats_and_Dogs, Index = 0, Count = null
# SUBMIT FILE NAME : preprocess1_py_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=f3cf816e-fbe7-4dba-8114-b1745340313a PEGASUS_WF_LABEL=Cats_and_Dogs PEGASUS_DAG_JOB_ID=preprocess1_py_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/preprocess1_py_ID0000001.err
executable = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/preprocess1_py_ID0000001.sh
initialdir = /home/scitech/shared-data/CatsAndDogs/wf-scratch/LOCAL/scitech/pegasus/Cats_and_Dogs/run0001
log = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/Cats_and_Dogs-0.log
notification = NEVER
output = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001//00/00/preprocess1_py_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = Cat4.jpg,Cat9.jpg,Dog3.jpg,Dog5.jpg,Dog0.jpg,Dog1.jpg,Cat1.jpg,Dog7.jpg,Cat5.jpg,Cat7.jpg,Dog9.jpg,Dog4.jpg,Cat3.jpg,Dog2.jpg,Cat0.jpg,preprocess1_py,Cat2.jpg,Dog6.jpg,Cat8.jpg,Dog8.jpg,Cat6.jpg,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = resized_Dog9.jpg,resized_Cat8.jpg,resized_Dog2.jpg,resized_Cat6.jpg,resized_Dog0.jpg,resized_Cat0.jpg,labels.txt,resized_images.txt,resized_Cat2.jpg,resized_Dog4.jpg,resized_Cat4.jpg,resized_Dog8.jpg,resized_Dog6.jpg,resized_Dog3.jpg,resized_Cat9.jpg,resized_Cat1.jpg,resized_Dog1.jpg,resized_Cat7.jpg,resized_Cat5.jpg,resized_Dog5.jpg,resized_Cat3.jpg,resized_Dog7.jpg
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "f3cf816e-fbe7-4dba-8114-b1745340313a"
+pegasus_wf_uuid = "f3cf816e-fbe7-4dba-8114-b1745340313a"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Cats_and_Dogs-0"
+pegasus_wf_time = "20201001T174430+0000"
+pegasus_wf_xformation = "preprocess1.py"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "preprocess1_py_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
