x-pegasus: {apiLang: python, createdBy: scitech, createdOn: '07-10-20 12:25:55'}
pegasus: '5.0'
name: helloworld
jobs:
- type: job
  name: echo
  id: ID0000001
  stdout: out.txt
  arguments: [Hello World!!!]
  uses:
  - {lfn: out.txt, type: output, stageOut: true, registerReplica: true}
jobDependencies: []
