######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : blackdiamond, Index = 0, Count = null
# SUBMIT FILE NAME : cleanup_blackdiamond_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a6f6cbed-2e41-4dfb-8efd-d3439c9c5056 PEGASUS_WF_LABEL=blackdiamond PEGASUS_DAG_JOB_ID=cleanup_blackdiamond_0_local PEGASUS_SITE=local PEGASUS_BIN_DIR=/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::cleanup -N null -i - -R local  -L blackdiamond -T 2020-07-10T21:45:00+00:00 pegasus-transfer "
error = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001//00/00/cleanup_blackdiamond_0_local.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-local.sh
input = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001//00/00/cleanup_blackdiamond_0_local.in
log = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/blackdiamond-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001//00/00/cleanup_blackdiamond_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a6f6cbed-2e41-4dfb-8efd-d3439c9c5056"
+pegasus_wf_uuid = "a6f6cbed-2e41-4dfb-8efd-d3439c9c5056"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "blackdiamond-0"
+pegasus_wf_time = "20200710T214500+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_blackdiamond_0_local"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
