######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : blackdiamond, Index = 0, Count = null
# SUBMIT FILE NAME : preprocess_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a6f6cbed-2e41-4dfb-8efd-d3439c9c5056 PEGASUS_WF_LABEL=blackdiamond PEGASUS_DAG_JOB_ID=preprocess_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001//00/00/preprocess_ID0000001.err
executable = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/00/00/preprocess_ID0000001.sh
initialdir = /home/scitech/shared-data/sample-black-diamond-wf/wf-scratch/LOCAL/scitech/pegasus/blackdiamond/run0001
log = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/blackdiamond-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001//00/00/preprocess_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = f.a,/home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/00/00/preprocess_ID0000001.in.meta,/home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/sample-black-diamond-wf/scitech/pegasus/blackdiamond/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = f.b2,f.b1
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a6f6cbed-2e41-4dfb-8efd-d3439c9c5056"
+pegasus_wf_uuid = "a6f6cbed-2e41-4dfb-8efd-d3439c9c5056"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "blackdiamond-0"
+pegasus_wf_time = "20200710T214500+0000"
+pegasus_wf_xformation = "preprocess"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "preprocess_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
