x-pegasus: {apiLang: python, createdBy: scitech, createdOn: '07-16-20T10:19:18Z'}
pegasus: '5.0'
name: add_thumbs
jobs:
- type: job
  name: Thumbs_up
  id: ID0000001
  arguments: [input.txt, output.txt]
  uses:
  - {lfn: output.txt, type: output, stageOut: true, registerReplica: true}
  - {lfn: input.txt, type: input}
jobDependencies: []
