######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Even_Odd, Index = 0, Count = null
# SUBMIT FILE NAME : separate_py_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=899f719b-8f6a-4221-87c1-553d4d9d846b PEGASUS_WF_LABEL=Even_Odd PEGASUS_DAG_JOB_ID=separate_py_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005//00/00/separate_py_ID0000001.err
executable = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005/00/00/separate_py_ID0000001.sh
initialdir = /home/scitech/shared-data/Workflow/Workflow3/wf-scratch/LOCAL/scitech/pegasus/Even_Odd/run0005
log = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005/Even_Odd-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005//00/00/separate_py_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = nums4.txt,nums3.txt,separate_py,nums1.txt,nums2.txt,nums5.txt,/home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0005/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = odd.txt,even.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "899f719b-8f6a-4221-87c1-553d4d9d846b"
+pegasus_wf_uuid = "899f719b-8f6a-4221-87c1-553d4d9d846b"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Even_Odd-0"
+pegasus_wf_time = "20200713T200513+0000"
+pegasus_wf_xformation = "separate.py"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "separate_py_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
