######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Increment, Index = 0, Count = null
# SUBMIT FILE NAME : increment_py_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=de33a8a2-9f99-4f6a-894e-478c54fe62a5 PEGASUS_WF_LABEL=Increment PEGASUS_DAG_JOB_ID=increment_py_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003//00/00/increment_py_ID0000001.err
executable = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003/00/00/increment_py_ID0000001.sh
initialdir = /home/scitech/shared-data/Workflow/Workflow2/wf-scratch/LOCAL/scitech/pegasus/Increment/run0003
log = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003/Increment-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003//00/00/increment_py_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = input.txt,increment_py,/home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/Workflow/Workflow2/scitech/pegasus/Increment/run0003/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = backup.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "de33a8a2-9f99-4f6a-894e-478c54fe62a5"
+pegasus_wf_uuid = "de33a8a2-9f99-4f6a-894e-478c54fe62a5"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Increment-0"
+pegasus_wf_time = "20200712T061241+0000"
+pegasus_wf_xformation = "increment.py"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "increment_py_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
