######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : helloworld, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3d224b5c-8d0c-4238-a3fb-b197a6cf7fe3 PEGASUS_WF_LABEL=helloworld PEGASUS_DAG_JOB_ID=register_local_0_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L helloworld -T 2020-07-22T19:00:02+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003/pegasus.5109005481121537847.properties -v --meta /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003/00/00/echo_ID0000001.meta --insert /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003/00/00/register_local_0_0.in"
error = /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003//00/00/register_local_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003/helloworld-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow1/scitech/pegasus/helloworld/run0003//00/00/register_local_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3d224b5c-8d0c-4238-a3fb-b197a6cf7fe3"
+pegasus_wf_uuid = "3d224b5c-8d0c-4238-a3fb-b197a6cf7fe3"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "helloworld-0"
+pegasus_wf_time = "20200722T190003+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_0_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
