######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : checkpoint-wf, Index = 0, Count = null
# SUBMIT FILE NAME : print_nums1_py_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=9de2567c-743f-4ffc-8188-7b646fa1f01d PEGASUS_WF_LABEL=checkpoint-wf PEGASUS_DAG_JOB_ID=print_nums1_py_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004//00/00/print_nums1_py_ID0000001.err
executable = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004/00/00/print_nums1_py_ID0000001.sh
initialdir = /home/scitech/shared-data/Workflow5/wf-scratch/LOCAL/scitech/pegasus/checkpoint-wf/run0004
log = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004/checkpoint-wf-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004//00/00/print_nums1_py_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = print_nums1_py,saved_stated.txt,/home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/Workflow5/scitech/pegasus/checkpoint-wf/run0004/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = output.txt,saved_stated.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "9de2567c-743f-4ffc-8188-7b646fa1f01d"
+pegasus_wf_uuid = "9de2567c-743f-4ffc-8188-7b646fa1f01d"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "checkpoint-wf-0"
+pegasus_wf_time = "20200720T181132+0000"
+pegasus_wf_xformation = "print_nums1.py"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "print_nums1_py_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
