######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : add_thumbs, Index = 0, Count = null
# SUBMIT FILE NAME : Thumbs_up_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a3fbe68e-4bd0-4207-875a-fb76ce8e6c3d PEGASUS_WF_LABEL=add_thumbs PEGASUS_DAG_JOB_ID=Thumbs_up_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006//00/00/Thumbs_up_ID0000001.err
executable = /home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006/00/00/Thumbs_up_ID0000001.sh
initialdir = /home/scitech/shared-data/Workflow/Workflow4/wf-scratch/LOCAL/scitech/pegasus/add_thumbs/run0006
log = /home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006/add_thumbs-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006//00/00/Thumbs_up_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = input.txt,tools-container,/home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/Workflow/Workflow4/scitech/pegasus/add_thumbs/run0006/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = output.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a3fbe68e-4bd0-4207-875a-fb76ce8e6c3d"
+pegasus_wf_uuid = "a3fbe68e-4bd0-4207-875a-fb76ce8e6c3d"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "add_thumbs-0"
+pegasus_wf_time = "20200716T015543+0000"
+pegasus_wf_xformation = "Thumbs_up"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "Thumbs_up_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
