######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Cats_and_Dogs, Index = 0, Count = null
# SUBMIT FILE NAME : VGG_model_py_ID0000004.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=fa9f12dc-85d1-44a7-b5cf-9f06286643e5 PEGASUS_WF_LABEL=Cats_and_Dogs PEGASUS_DAG_JOB_ID=VGG_model_py_ID0000004 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002//00/00/VGG_model_py_ID0000004.err
executable = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002/00/00/VGG_model_py_ID0000004.sh
initialdir = /home/scitech/shared-data/CatsAndDogs/wf-scratch/LOCAL/scitech/pegasus/Cats_and_Dogs/run0002
log = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002/Cats_and_Dogs-0.log
notification = NEVER
output = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002//00/00/VGG_model_py_ID0000004.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = VGG_model_py,testing.pkl,validation.pkl,training.pkl,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002/00/00/Data_Split_py_ID0000003.meta,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002/00/00/stage_in_remote_local_3_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0002/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = model.h5.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "fa9f12dc-85d1-44a7-b5cf-9f06286643e5"
+pegasus_wf_uuid = "fa9f12dc-85d1-44a7-b5cf-9f06286643e5"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Cats_and_Dogs-0"
+pegasus_wf_time = "20200807T190452+0000"
+pegasus_wf_xformation = "VGG_model.py"
+pegasus_wf_dax_job_id = "ID0000004"
+pegasus_wf_dag_job_id = "VGG_model_py_ID0000004"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
