######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Even_Odd, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=cbaa5df9-8b0e-4464-af02-dbf7e0088544 PEGASUS_WF_LABEL=Even_Odd PEGASUS_DAG_JOB_ID=register_local_2_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L Even_Odd -T 2020-07-13T19:51:21+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003/pegasus.4836824759494652213.properties -v --meta /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003/00/00/tar_ID0000004.meta --insert /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003/00/00/register_local_2_0.in"
error = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003//00/00/register_local_2_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003/Even_Odd-0.log
notification = NEVER
output = /home/scitech/shared-data/Workflow/Workflow3/scitech/pegasus/Even_Odd/run0003//00/00/register_local_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "cbaa5df9-8b0e-4464-af02-dbf7e0088544"
+pegasus_wf_uuid = "cbaa5df9-8b0e-4464-af02-dbf7e0088544"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Even_Odd-0"
+pegasus_wf_time = "20200713T195122+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_2_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
