x-pegasus: {apiLang: python, createdBy: scitech, createdOn: '07-20-20T11:11:32Z'}
pegasus: '5.0'
name: checkpoint-wf
jobs:
- type: job
  name: print_nums1.py
  id: ID0000001
  stdout: output.txt
  arguments: [180]
  uses:
  - {lfn: output.txt, type: output, stageOut: true, registerReplica: true}
  - {lfn: saved_stated.txt, type: checkpoint, stageOut: true, registerReplica: true}
  profiles:
    pegasus: {checkpoint.time: 1, maxwalltime: 2}
jobDependencies: []
