x-pegasus: {apiLang: python, createdBy: scitech, createdOn: '07-23-20T09:56:10Z'}
pegasus: '5.0'
name: nested-dir-tutorial
jobs:
- type: job
  name: print_file_contents
  id: ID0000001
  stdout: out.txt
  arguments: []
  uses:
  - {lfn: dog_sounds.txt, type: input}
  - {lfn: out.txt, type: output, stageOut: true, registerReplica: true}
  - {lfn: cat_sounds.txt, type: input}
jobDependencies: []
