######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : Cats_and_Dogs, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=59900de0-38d5-4662-8de5-eb74ebc081d1 PEGASUS_WF_LABEL=Cats_and_Dogs PEGASUS_DAG_JOB_ID=register_local_0_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L Cats_and_Dogs -T 2020-09-14T20:31:28+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013/pegasus.3978120886015001928.properties -v --meta /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013/00/00/preprocess1_py_ID0000001.meta --insert /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013/00/00/register_local_0_0.in"
error = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013//00/00/register_local_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013/Cats_and_Dogs-0.log
notification = NEVER
output = /home/scitech/shared-data/CatsAndDogs/scitech/pegasus/Cats_and_Dogs/run0013//00/00/register_local_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "59900de0-38d5-4662-8de5-eb74ebc081d1"
+pegasus_wf_uuid = "59900de0-38d5-4662-8de5-eb74ebc081d1"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "Cats_and_Dogs-0"
+pegasus_wf_time = "20200914T203129+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_0_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
