######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : nested-dir-tutorial, Index = 0, Count = null
# SUBMIT FILE NAME : print_file_contents_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a58d5bc5-5aa2-4824-a1ed-36f73d79abc8 PEGASUS_WF_LABEL=nested-dir-tutorial PEGASUS_DAG_JOB_ID=print_file_contents_ID0000001 PEGASUS_SITE=condorpool"
+TransferOutput = ""
+WantIOProxy = True
error = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/print_file_contents_ID0000001.err
executable = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/00/00/print_file_contents_ID0000001.sh
log = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/nested-dir-tutorial-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/print_file_contents_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/00/00/stage_in_local_stage_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "nested-dir-tutorial-0"
+pegasus_wf_time = "20200723T165611+0000"
+pegasus_wf_xformation = "print_file_contents"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "print_file_contents_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
