######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : nested-dir-tutorial, Index = 0, Count = null
# SUBMIT FILE NAME : register_stage_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a58d5bc5-5aa2-4824-a1ed-36f73d79abc8 PEGASUS_WF_LABEL=nested-dir-tutorial PEGASUS_DAG_JOB_ID=register_stage_0_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L nested-dir-tutorial -T 2020-07-23T16:56:10+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/pegasus.1099241611213702313.properties -v --meta /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/00/00/print_file_contents_ID0000001.meta --insert /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/00/00/register_stage_0_0.in"
error = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/register_stage_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/nested-dir-tutorial-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/register_stage_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "nested-dir-tutorial-0"
+pegasus_wf_time = "20200723T165611+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_stage_0_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
