######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : nested-dir-tutorial, Index = 0, Count = null
# SUBMIT FILE NAME : stage_out_local_stage_0_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=a58d5bc5-5aa2-4824-a1ed-36f73d79abc8 PEGASUS_WF_LABEL=nested-dir-tutorial PEGASUS_DAG_JOB_ID=stage_out_local_stage_0_0 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/00/00/print_file_contents_ID0000001.meta, PEGASUS_BIN_DIR=/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L nested-dir-tutorial -T 2020-07-23T16:56:10+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-transfer  --threads 2 "
error = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/stage_out_local_stage_0_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-local.sh
input = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/stage_out_local_stage_0_0.in
log = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001/nested-dir-tutorial-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-deep-lfn-nonsharedfs-wf/scitech/pegasus/nested-dir-tutorial/run0001//00/00/stage_out_local_stage_0_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 900
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_wf_uuid = "a58d5bc5-5aa2-4824-a1ed-36f73d79abc8"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "nested-dir-tutorial-0"
+pegasus_wf_time = "20200723T165611+0000"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_out_local_stage_0_0"
+pegasus_job_class = 3
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
