######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : checkpoint-wf, Index = 0, Count = null
# SUBMIT FILE NAME : checkpoint_program_py_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=fb9dc136-ae69-4b51-8c13-fdff6be6cbb5 PEGASUS_WF_LABEL=checkpoint-wf PEGASUS_DAG_JOB_ID=checkpoint_program_py_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002//00/00/checkpoint_program_py_ID0000001.err
executable = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002/00/00/checkpoint_program_py_ID0000001.sh
initialdir = /home/scitech/shared-data/sample-checkpoint-condorio-wf/wf-scratch/LOCAL/scitech/pegasus/checkpoint-wf/run0002
log = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002/checkpoint-wf-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002//00/00/checkpoint_program_py_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = checkpoint_program_py,saved_state.txt,/home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002/00/00/stage_in_remote_local_0_0.meta,/home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/sample-checkpoint-condorio-wf/scitech/pegasus/checkpoint-wf/run0002/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = output.txt,saved_state.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "fb9dc136-ae69-4b51-8c13-fdff6be6cbb5"
+pegasus_wf_uuid = "fb9dc136-ae69-4b51-8c13-fdff6be6cbb5"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "checkpoint-wf-0"
+pegasus_wf_time = "20200720T171645+0000"
+pegasus_wf_xformation = "checkpoint_program.py"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "checkpoint_program_py_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
