x-pegasus: {apiLang: python, createdBy: scitech, createdOn: '07-11-20T23:02:13Z'}
pegasus: '5.0'
name: Increment
jobs:
- type: job
  name: increment.py
  id: ID0000001
  arguments: [input.txt, backup.txt]
  uses:
  - {lfn: input.txt, type: input}
  - {lfn: backup.txt, type: output, stageOut: true, registerReplica: true}
jobDependencies: []
