######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : harry-potter-text-analysis, Index = 0, Count = null
# SUBMIT FILE NAME : plot_ID0000003.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=618d7b9c-5599-434b-bc77-bd43d9250360 PEGASUS_WF_LABEL=harry-potter-text-analysis PEGASUS_DAG_JOB_ID=plot_ID0000003 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001//00/00/plot_ID0000003.err
executable = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001/00/00/plot_ID0000003.sh
initialdir = /home/scitech/shared-data/sample-text-analysis-wf/wf-scratch/LOCAL/scitech/pegasus/harry-potter-text-analysis/run0001
log = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001/harry-potter-text-analysis-0.log
notification = NEVER
output = /home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001//00/00/plot_ID0000003.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = wc-sorted.txt,plot,/home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001/00/00/stage_in_remote_local_2_0.meta,/home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001/00/00/sort_ID0000002.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/sample-text-analysis-wf/scitech/pegasus/harry-potter-text-analysis/run0001/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = plot.png
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "618d7b9c-5599-434b-bc77-bd43d9250360"
+pegasus_wf_uuid = "618d7b9c-5599-434b-bc77-bd43d9250360"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "harry-potter-text-analysis-0"
+pegasus_wf_time = "20200810T204624+0000"
+pegasus_wf_xformation = "plot"
+pegasus_wf_dax_job_id = "ID0000003"
+pegasus_wf_dag_job_id = "plot_ID0000003"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
